/* ============================================================
   CURADORIA — os dados (09/out/2026, PERFIL.md item 74)
   "Temos muito conteúdo, mas nada pra direcionar; que mostre quem é o curador, pra acabar com
   coisas falsas e que privam e pedem dinheiro."
   Cada curadoria diz: quem escolheu (a ficha do curador), quando, como foi feita e com que fontes.
   A primeira é a do Vitor: a inauguração da Curadoria e a estreia do Portal Solar.
   Os fatos foram conferidos em 09/out/2026 (fontes no fim de cada parte). O texto da abertura foi
   montado das palavras do curador; em 09/out ele aceitou tudo ("SIM SIM SIM! FAÇA TUDO!", item 75),
   inclusive os dois assuntos propostos (as Bachianas e a Capela Rothko), e segue alterando.
   ============================================================ */
(function (raiz) {
  'use strict';

  var W = 'https://en.wikipedia.org/wiki/';
  var WP = 'https://pt.wikipedia.org/wiki/';

  var POSTS = [{
    slug: 'a-praca-o-pavao-e-o-eter',
    numero: 1,
    titulo: 'A praça, o pavão e o éter',
    sub: 'Inauguração da Curadoria e estreia do Portal Solar',
    data: '2026-10-09',
    curador: { nome: 'Vitor de Mantova', papel: 'curador', ficha: 'eu.html#ficha' },
    estado: 'aberta: o curador vai alterando e melhorando',
    como: 'A abertura foi montada das palavras do curador (a mensagem de 09/out/2026). Os quatro assuntos e o glossário foram escritos com o Claude, a partir de fontes públicas conferidas no mesmo dia (listadas em cada parte). Nada aqui é pago, patrocinado ou escolhido por algoritmo: é a escolha de uma pessoa, com nome e porquê.',
    capa: { cor: '#14130F', sol: '#E9822A' },

    abertura: [
      'Começo pela emoção, porque foi ela que me trouxe até aqui: a **linhagem de Scriabin**. O meu amado **Roslavets**, o perfeito **Sorabji**, e todos os outros: amo todos.',
      '**Charles Villiers Stanford**, **César Franck** e **Taneyev** fizeram o mesmo: cada um pegou a língua da sua terra e a costurou na grande tradição, e a devolveu maior. Quem mais? **Enescu**. E quem segue Enescu? Euzinho! **Brahms**, e muitos…',
      'Como é lindo: essa tradição que passa através do éter para muitas nações, vilas e seres. Faz os animais dançarem e as árvores sorrirem. **Vamos reverter o desastre do mundo** :)',
      'Por isso esta Curadoria existe. Temos muito conteúdo e quase nada que direcione; e o que direciona, muitas vezes, é falso, esconde quem escolheu, priva e pede dinheiro. Aqui, cada escolha tem nome, data e porquê. Esta é a primeira, e com ela o Portal Solar se abre.',
    ],

    /* a linhagem da abertura: quem fez o mesmo, em que terra, com que obra */
    linhagem: [
      { nome: 'Johannes Brahms', anos: '1833–1897', terra: 'Alemanha → Viena', obra: 'Danças Húngaras (1869); Um Réquiem Alemão (1868)', fez: 'o contraponto de Bach e o canto do povo na mesma página', url: W + 'Johannes_Brahms' },
      { nome: 'César Franck', anos: '1822–1890', terra: 'Bélgica → Paris', obra: 'Sinfonia em ré menor (1888)', fez: 'o órgão de Sainte-Clotilde e a forma cíclica: um tema que volta transformado', url: W + 'C%C3%A9sar_Franck' },
      { nome: 'Charles Villiers Stanford', anos: '1852–1924', terra: 'Irlanda → Londres', obra: 'as seis Rapsódias Irlandesas', fez: 'a Irlanda na sinfonia; professor de Vaughan Williams, Holst e Bridge no Royal College of Music', url: W + 'Charles_Villiers_Stanford' },
      { nome: 'Sergei Taneyev', anos: '1856–1915', terra: 'Rússia', obra: 'Contraponto invertível no estilo estrito (tratado, 1909)', fez: 'o contraponto como disciplina russa; professor de Scriabin e de Rachmaninoff', url: W + 'Sergei_Taneyev' },
      { nome: 'Alexander Scriabin', anos: '1872–1915', terra: 'Rússia', obra: 'Prometeu, o Poema do Fogo (1910)', fez: 'o acorde místico e uma parte escrita para luzes: a música que quer ser cor', url: W + 'Alexander_Scriabin' },
      { nome: 'Nikolai Roslavets', anos: '1881–1944', terra: 'Império Russo', obra: 'os "acordes sintéticos" (anos 1910)', fez: 'um sistema próprio de organizar os sons, depois de Scriabin; marginalizado a partir de 1930 e redescoberto no fim do século', url: W + 'Nikolai_Roslavets' },
      { nome: 'George Enescu', anos: '1881–1955', terra: 'Romênia → Paris', obra: 'Rapsódias Romenas (1901); a ópera Œdipe (1936)', fez: 'o canto romeno na grande forma; professor de Yehudi Menuhin', url: W + 'George_Enescu' },
      { nome: 'Kaikhosru Sorabji', anos: '1892–1988', terra: 'Inglaterra', obra: 'Opus clavicembalisticum (1930), umas quatro horas de piano', fez: 'a escrita mais rica do piano no século; por décadas desencorajou que a tocassem em público', url: W + 'Kaikhosru_Shapurji_Sorabji' },
      { nome: 'Heitor Villa-Lobos', anos: '1887–1959', terra: 'Brasil', obra: 'Bachianas Brasileiras (1930–1945)', fez: 'Bach e o Brasil na mesma suíte (veja a terceira parte)', url: WP + 'Bachianas_Brasileiras' },
      { nome: 'e quem segue', anos: 'agora', terra: 'Campinas', obra: 'o Portal Solar', fez: 'quem segue Enescu? euzinho!', url: null, voce: true },
    ],

    partes: [
      {
        id: 'praca',
        titulo: 'A praça do Teatro',
        lugar: 'Teatralnaya, Moscou',
        lead: 'Uma praça com três teatros, desenhada em volta de um deles. Por ela passaram compositores de muitos países, e dela saíram obras que hoje são de todo mundo.',
        texto: [
          'A **Praça do Teatro** nasceu depois do incêndio de Moscou de 1812, quando o rio Neglinnaya foi posto num canal debaixo da terra (ele ainda corre ali, na diagonal, sob o jardim). Nos anos 1820, o arquiteto **Joseph Bové** a desenhou simétrica, com o **Bolshoi** no centro. Hoje ela leva o nome de três teatros: o Bolshoi, o **Maly** e o Teatro Acadêmico da Juventude.',
          'A companhia é mais velha que o prédio: em março de **1776**, o príncipe Piotr Urusov recebeu o privilégio de dirigir espetáculos em Moscou, e logo se associou a um inglês, **Michael Maddox**. O Teatro Petrovsky abriu em 1780 e queimou em 1805. O prédio de Bové abriu em **janeiro de 1825**; outro incêndio, em 1853, deixou de pé quase só as paredes, e o arquiteto **Alberto Cavos** (de família veneziana) o reergueu para a coroação de Alexandre II, em **1856**. A grande restauração durou de 2005 a 2011.',
          'Ali estreou **O Lago dos Cisnes**, de **Tchaikovsky**, em **1877**. Ali estreou **Aleko**, a ópera de formatura de **Rachmaninoff**, em **1893**, e o próprio Rachmaninoff regeu no Bolshoi de 1904 a 1906. Ali estrearam **A Papoula Vermelha**, de Glière (1927), e **Cinderela**, de Prokofiev (1945).',
          'E os de fora: **Wagner** regeu em Moscou em 1863 (Tchaikovsky lembraria anos depois do Liebestod regido por ele); **Berlioz**, em janeiro de **1868**, regeu com quinhentos músicos no Manège e regeu também no salão da Assembleia da Nobreza, e no banquete quem ergueu o brinde foi o jovem Tchaikovsky; **Dvořák** regeu as suas obras em Moscou em março de **1890**, a convite de Tchaikovsky. O salão da Assembleia da Nobreza (o atual Salão das Colunas, de Matvey Kazakov, 1784–87) fica na esquina vizinha da praça, e desde 1860 recebia os concertos de **Nikolai Rubinstein**.',
          'É por isso que a praça é uma boa imagem do que a abertura chama de "éter": um empresário inglês, um arquiteto de família italiana, a dança com nomes franceses, a sinfonia alemã, compositores tchecos e franceses no pódio, e de volta, para o mundo inteiro, uma música russa que já não pertence a ninguém. A sacralidade da música clássica está nesse caráter universal: ela passa de mão em mão sem perder o nome de quem a fez.',
        ],
        ouvir: [
          ['Tchaikovsky', 'O Lago dos Cisnes, ato II', '1877'],
          ['Rachmaninoff', 'Aleko, a cavatina', '1893'],
          ['Prokofiev', 'Cinderela, a valsa', '1945'],
          ['Scriabin', 'Prometeu, o Poema do Fogo', '1910'],
        ],
        ler: [
          ['Orlando Figes', 'Natasha’s Dance: A Cultural History of Russia', '2002'],
          ['Richard Taruskin', 'Defining Russia Musically', '1997'],
          ['Simon Morrison', 'Bolshoi Confidential', '2016'],
          ['Rosamund Bartlett', 'Wagner and Russia', '1995'],
        ],
        fontes: [['Bolshoi Theatre (Wikipédia)', W + 'Bolshoi_Theatre'], ['Theatre Square, Moscou (Wikipédia)', W + 'Theatre_Square_(Moscow)'], ['House of the Unions (Wikipédia)', W + 'House_of_the_Unions'], ['Tchaikovsky Research: Wagner', 'https://en.tchaikovsky-research.net/pages/Richard_Wagner'], ['Dvořák como regente (antonin-dvorak.cz)', 'https://www.antonin-dvorak.cz/en/life/dvorak-as-a-performer/conductor-performances/']],
      },
      {
        id: 'pavao',
        titulo: 'A Sala do Pavão',
        lugar: 'Londres → Detroit → Washington',
        lead: 'Uma sala de jantar que virou a melhor introdução à arte, à arquitetura e a como o mundo gira: um magnata, um pintor, porcelana da China, uma briga por dinheiro e um museu gratuito no fim.',
        texto: [
          'Em Londres, no número 49 de Prince’s Gate, o armador de Liverpool **Frederick Richards Leyland** queria uma sala para a sua coleção de porcelana chinesa azul e branca (do período Kangxi). O arquiteto **Thomas Jeckyll** desenhou prateleiras de nogueira, em treliça, como um grande armário de porcelana; sobre a lareira ficou um quadro de **James McNeill Whistler**, *A Princesa do País da Porcelana*.',
          'Jeckyll adoeceu e deixou a obra. Whistler, chamado para retoques, pintou a sala inteira em azul e ouro, com pavões, em **1876–77**, enquanto o dono estava fora. Pediu dois mil guinéus; Leyland pagou **mil libras**, a metade, e em libras (a moeda dos comerciantes), não em guinéus (a dos cavalheiros e dos artistas). Whistler respondeu com a pintura na parede oposta: dois pavões brigando, um deles com moedas de prata aos pés. O título é *A Arte e o Dinheiro; ou, A História da Sala*.',
          'Em **1904**, o industrial **Charles Lang Freer**, de Detroit (vagões de trem), comprou a sala inteira e a remontou em casa. Depois da morte dele, em 1919, ela foi para Washington, para o museu que ele deu ao país: a **Freer Gallery of Art**, aberta ao público em **1923**, de graça.',
          'O que a sala ensina: o **esteticismo** (a arte pela arte, que não precisa servir a nada), o **japonismo** e a porcelana que atravessou oceanos pelo comércio; o mecenas que paga e o artista que zomba de quem paga; e o fim da história, quando o luxo privado vira patrimônio público. A briga de Whistler continuou nos tribunais: em 1878 ele processou o crítico John Ruskin, que tinha dito que ele "atirou um pote de tinta na cara do público"; ganhou um quarto de pêni e faliu no ano seguinte.',
        ],
        ouvir: [
          ['Debussy', 'Nocturnes (o título vem dos Noturnos de Whistler)', '1899'],
          ['Ravel', 'Ma mère l’Oye, "Laideronnette, imperatriz dos pagodes"', '1910'],
        ],
        ler: [
          ['Linda Merrill', 'The Peacock Room: A Cultural Biography', '1998'],
          ['James McNeill Whistler', 'The Gentle Art of Making Enemies', '1890'],
          ['Walter Pater', 'O Renascimento (Studies in the History of the Renaissance)', '1873'],
          ['Oscar Wilde', 'The Decay of Lying', '1889'],
        ],
        fontes: [['Smithsonian: Peacocks, Four Men in Three Acts', 'https://asia-archive.si.edu/peacocks-four-men-in-three-acts'], ['Peacock Room (Wikipédia)', W + 'Peacock_Room'], ['Smithsonian: The Peacock Room (Filthy Lucre)', 'https://archive.asia.si.edu/filthylucre/peacock-room.asp']],
      },
      {
        id: 'bachianas',
        titulo: 'As Bachianas e a Semana de 22',
        lugar: 'Theatro Municipal de São Paulo',
        lead: 'O Brasil fez o mesmo que Stanford, Franck, Taneyev e Enescu: levou a música da sua terra para dentro da grande tradição, e a tradição saiu brasileira. (Assunto proposto pelo Claude e aceito pelo curador em 9 de outubro de 2026.)',
        texto: [
          'Em **fevereiro de 1922**, em três noites (dias 13, 15 e 17), o **Theatro Municipal de São Paulo** (aberto em 1911) recebeu a **Semana de Arte Moderna**: Graça Aranha falou da emoção estética, Ronald de Carvalho leu *Os Sapos*, de Manuel Bandeira, sob vaias, e na última noite **Villa-Lobos** entrou de casaca, com um sapato num pé e um chinelo no outro (por causa de um calo, diz-se), e foi vaiado também.',
          'Seis anos depois, **Oswald de Andrade** publicou o **Manifesto Antropófago** (1928): "Tupi, or not tupi, that is the question". Devorar o que vem de fora e transformá-lo em coisa nossa. É exatamente a tradição que passa pelo éter.',
          'Villa-Lobos fez isso na música: as nove **Bachianas Brasileiras** (1930–1945) juntam Bach ao choro, à modinha e ao sertão. Ele via em Bach uma "fonte folclórica universal", intermediária entre todos os povos. A *Ária (Cantilena)* da Bachianas nº 5 (1938), para soprano e oito violoncelos, é talvez a música brasileira mais ouvida no mundo.',
        ],
        ouvir: [
          ['Villa-Lobos', 'Bachianas Brasileiras nº 5, Ária (Cantilena)', '1938'],
          ['Villa-Lobos', 'Bachianas Brasileiras nº 2, O Trenzinho do Caipira', '1930'],
          ['Villa-Lobos', 'Choros nº 10, Rasga o Coração', '1926'],
        ],
        ler: [
          ['Mário de Andrade', 'Ensaio sobre a música brasileira', '1928'],
          ['Oswald de Andrade', 'Manifesto Antropófago', '1928'],
          ['Vasco Mariz', 'Heitor Villa-Lobos, compositor brasileiro', '1949'],
          ['Paulo Renato Guérios', 'Heitor Villa-Lobos: o caminho sinuoso da predestinação', '2003'],
        ],
        fontes: [['Semana de Arte Moderna (Wikipédia)', WP + 'Semana_de_Arte_Moderna'], ['Bachianas Brasileiras (Wikipédia)', WP + 'Bachianas_Brasileiras'], ['Theatro Municipal de São Paulo (Wikipédia)', WP + 'Theatro_Municipal_de_S%C3%A3o_Paulo'], ['Revista Música (USP): as Bachianas e a "fonte folclórica universal"', 'https://periodicos.usp.br/revistamusica/article/download/146584/146545/307891']],
      },
      {
        id: 'rothko',
        titulo: 'A Capela Rothko',
        lugar: 'Houston',
        lead: 'O sagrado sem imagem: do Quadrado Negro pendurado no canto dos ícones (1915) às telas escuras de Rothko numa capela aberta a todas as fés e a nenhuma (1971). (Assunto proposto pelo Claude e aceito pelo curador em 9 de outubro de 2026.)',
        texto: [
          'Em **1915**, na exposição *0,10*, em Petrogrado, **Kazimir Malevich** pendurou o **Quadrado Negro** no canto alto da sala, onde as casas russas põem o ícone. Ele o chamou de ponto zero da pintura. É a marca do Portal Solar.',
          'Meio século depois, os colecionadores **John e Dominique de Menil** encomendaram a **Mark Rothko** catorze telas para uma capela em Houston. Rothko morreu em 1970; a capela foi inaugurada em **fevereiro de 1971**, aberta a pessoas de todas as religiões e de nenhuma. No espelho d’água, o *Obelisco Quebrado* de Barnett Newman é dedicado a Martin Luther King Jr.',
          'Em **1972**, a capela ouviu pela primeira vez a peça que **Morton Feldman** escreveu para ela, *Rothko Chapel*: viola, celesta, percussão, soprano, contralto e coro, quase em silêncio. A fortuna dos de Menil vinha do petróleo; o destino dela foi a contemplação e os direitos humanos. É o outro fim possível da história da Sala do Pavão.',
        ],
        ouvir: [
          ['Morton Feldman', 'Rothko Chapel', '1971'],
          ['Arvo Pärt', 'Spiegel im Spiegel', '1978'],
        ],
        ler: [
          ['Ryan Dohoney', 'Saving Abstraction: Morton Feldman, the de Menils, and the Rothko Chapel', '2019'],
          ['Sheldon Nodelman', 'The Rothko Chapel Paintings: Origins, Structure, Meaning', '1997'],
          ['Mark Rothko', 'A realidade do artista (The Artist’s Reality)', '2004'],
          ['Wassily Kandinsky', 'Do espiritual na arte', '1911'],
        ],
        fontes: [['Rothko Chapel (Wikipédia)', W + 'Rothko_Chapel'], ['Black Square (Wikipédia)', W + 'Black_Square_(painting)'], ['Broken Obelisk (Wikipédia)', W + 'Broken_Obelisk'], ['Morton Feldman (Wikipédia)', W + 'Morton_Feldman']],
      },
    ],

    /* O GLOSSÁRIO: 40 termos que expandem, aproximam e conectam.
       ano: o ano de referência (negativo = antes de Cristo) · area: estetica | musica | movimentos | instituicoes | sentidos
       sente: o sentimento que o termo desperta (para a roda dos sentimentos) · liga: os termos vizinhos */
    glossario: [
      { id: 'obra-total', termo: 'Obra de arte total', original: 'Gesamtkunstwerk', ano: 1849, quando: '1827 · 1849', area: 'sentidos', sente: 'êxtase',
        texto: 'A obra que junta todas as artes numa só: música, poesia, cena, arquitetura, luz. A palavra aparece com o filósofo Trahndorff (1827), mas é Wagner quem a torna programa, em 1849. Bayreuth, o Prometeu de Scriabin e a Bauhaus são tentativas dela.',
        livros: [['Richard Wagner', 'A obra de arte do futuro', 1849], ['Richard Wagner', 'Ópera e drama', 1851], ['Walter Gropius', 'Manifesto da Bauhaus', 1919]], liga: ['leitmotiv', 'sinestesia', 'bauhaus', 'art-nouveau'] },
      { id: 'arte-pela-arte', termo: 'Arte pela arte', original: 'l’art pour l’art', ano: 1835, quando: '1818 · 1835', area: 'estetica', sente: 'deleite',
        texto: 'A arte não precisa servir à moral, à política nem ao mercado: o fim dela é ela mesma. A frase circula desde as aulas de Victor Cousin (1818); vira bandeira no prefácio de Gautier (1835) e chega a Pater, Whistler e Wilde.',
        livros: [['Théophile Gautier', 'Mademoiselle de Maupin (prefácio)', 1835], ['Walter Pater', 'O Renascimento', 1873], ['Oscar Wilde', 'O retrato de Dorian Gray (prefácio)', 1891]], liga: ['esteticismo', 'decadentismo', 'dandismo', 'belo'] },
      { id: 'sinestesia', termo: 'Sinestesia', original: 'syn + aisthesis, "sentir junto"', ano: 1857, quando: '1857 · 1910', area: 'sentidos', sente: 'êxtase',
        texto: 'Quando um sentido acorda outro: o som que tem cor, a vogal que tem tom. Na poesia, as "Correspondências" de Baudelaire e as "Vogais" de Rimbaud; na música, Scriabin escreve uma parte para luzes no Prometeu (1910); na pintura, Kandinsky ouve as cores.',
        livros: [['Charles Baudelaire', 'As flores do mal ("Correspondências")', 1857], ['Wassily Kandinsky', 'Do espiritual na arte', 1911], ['Richard Cytowic', 'The Man Who Tasted Shapes', 1993]], liga: ['correspondencias', 'acorde-mistico', 'obra-total', 'espiritual'] },
      { id: 'decadentismo', termo: 'Decadentismo', original: 'décadence', ano: 1884, quando: '1883 · 1886', area: 'movimentos', sente: 'melancolia',
        texto: 'O fim de século que se sente o fim de um império: refinamento, artifício, tédio, beleza mórbida. Verlaine escreve "Sou o Império no fim da decadência" (1883); Huysmans faz do herói de Às avessas (1884) um colecionador de sensações raras.',
        livros: [['J.-K. Huysmans', 'Às avessas', 1884], ['Paul Verlaine', 'Jadis et naguère ("Langueur")', 1884], ['Mario Praz', 'A carne, a morte e o diabo na literatura romântica', 1930]], liga: ['simbolismo', 'arte-pela-arte', 'dandismo', 'spleen'] },
      { id: 'simbolismo', termo: 'Simbolismo', original: 'symbolisme', ano: 1886, quando: '1886', area: 'movimentos', sente: 'mistério',
        texto: 'Sugerir em vez de dizer: a poesia como música e como enigma. O manifesto de Jean Moréas sai no Le Figaro em 18 de setembro de 1886; Mallarmé é o mestre. No Brasil, Cruz e Sousa abre o movimento com Broquéis (1893).',
        livros: [['Jean Moréas', 'O Simbolismo (manifesto)', 1886], ['Cruz e Sousa', 'Broquéis', 1893], ['Edmund Wilson', 'O castelo de Axel', 1931]], liga: ['decadentismo', 'correspondencias', 'sinestesia'] },
      { id: 'esteticismo', termo: 'Esteticismo', original: 'Aesthetic movement', ano: 1873, quando: '1870 · 1890', area: 'movimentos', sente: 'deleite',
        texto: 'A beleza como valor da vida inteira: a casa, a roupa, o livro, a sala de jantar. Pater pede "arder sempre com essa chama dura, como uma gema"; Whistler e Wilde levam isso aos salões. A Sala do Pavão é o seu monumento.',
        livros: [['Walter Pater', 'O Renascimento', 1873], ['James McNeill Whistler', 'Ten O’Clock (conferência)', 1885], ['Oscar Wilde', 'Intenções', 1891]], liga: ['arte-pela-arte', 'japonismo', 'dandismo', 'art-nouveau'] },
      { id: 'japonismo', termo: 'Japonismo', original: 'japonisme', ano: 1872, quando: '1872 · 1891', area: 'movimentos', sente: 'encanto',
        texto: 'A paixão europeia pela arte japonesa depois da abertura dos portos do Japão: as gravuras ukiyo-e, a composição assimétrica, a cor chapada. O crítico Philippe Burty dá o nome (1872); Siegfried Bing publica a revista Le Japon artistique (1888–91). Van Gogh, Whistler e Monet bebem dali.',
        livros: [['Siegfried Bing (org.)', 'Le Japon artistique', 1888], ['Siegfried Wichmann', 'Japonisme', 1981]], liga: ['esteticismo', 'art-nouveau'] },
      { id: 'correspondencias', termo: 'Correspondências', original: 'correspondances', ano: 1857, quando: '1749 · 1857', area: 'sentidos', sente: 'mistério',
        texto: 'A ideia de que tudo no mundo responde a tudo: os perfumes, as cores e os sons "se respondem", e a natureza é "um templo" de símbolos. Vem do místico Swedenborg e vira poema em Baudelaire; é a raiz do simbolismo e da sinestesia.',
        livros: [['Emanuel Swedenborg', 'Arcana Coelestia', 1749], ['Charles Baudelaire', 'As flores do mal', 1857]], liga: ['sinestesia', 'simbolismo', 'eter'] },
      { id: 'sublime', termo: 'Sublime', original: 'hypsos · sublimis', ano: 1757, quando: 'séc. I · 1757 · 1790', area: 'estetica', sente: 'assombro',
        texto: 'O que é grande demais para nós e por isso nos eleva: a tempestade, o abismo, o céu estrelado, uma sinfonia. O tratado atribuído a Longino o define; Burke (1757) o separa do belo pelo medo deleitoso; Kant (1790) o põe na mente que se descobre maior que a natureza.',
        livros: [['Longino', 'Do sublime', 50], ['Edmund Burke', 'Investigação filosófica sobre a origem de nossas ideias do sublime e do belo', 1757], ['Immanuel Kant', 'Crítica da faculdade de julgar', 1790]], liga: ['belo', 'sagrado', 'contemplacao'] },
      { id: 'belo', termo: 'Belo', original: 'to kalon', ano: -380, quando: 'c. 380 a.C. · 1790', area: 'estetica', sente: 'deleite',
        texto: 'Para Platão, a escada que vai de um corpo bonito à Beleza em si (O Banquete). Para Kant, o que agrada sem interesse e "sem conceito". A pergunta atravessa tudo: o belo é do objeto ou de quem olha?',
        livros: [['Platão', 'O Banquete', -380], ['Immanuel Kant', 'Crítica da faculdade de julgar', 1790], ['Umberto Eco', 'História da beleza', 2004]], liga: ['sublime', 'arte-pela-arte', 'mimese'] },
      { id: 'mimese', termo: 'Mímese', original: 'mimesis', ano: -335, quando: 'c. 335 a.C. · 1946', area: 'estetica', sente: 'reconhecimento',
        texto: 'A arte como imitação, ou melhor, como recriação do mundo e das ações humanas. Aristóteles a defende na Poética contra a desconfiança de Platão; Erich Auerbach conta a história do realismo de Homero a Virginia Woolf.',
        livros: [['Aristóteles', 'Poética', -335], ['Erich Auerbach', 'Mimesis', 1946]], liga: ['catarse', 'belo', 'aura'] },
      { id: 'catarse', termo: 'Catarse', original: 'katharsis', ano: -335, quando: 'c. 335 a.C.', area: 'estetica', sente: 'alívio',
        texto: 'A purificação das emoções, a piedade e o temor, que a tragédia provoca no público. Aristóteles a cita uma vez, de passagem, e com essa linha só criou dois mil anos de discussão.',
        livros: [['Aristóteles', 'Poética', -335], ['Friedrich Nietzsche', 'O nascimento da tragédia', 1872]], liga: ['mimese', 'sagrado'] },
      { id: 'aura', termo: 'Aura', original: 'Aura', ano: 1935, quando: '1935–36', area: 'instituicoes', sente: 'nostalgia',
        texto: 'O "aqui e agora" da obra original, a sua presença única, que a reprodução técnica (a fotografia, o cinema) dissolve. Walter Benjamin vê na perda da aura um perigo e também uma libertação: a arte sai do altar e chega a todos.',
        livros: [['Walter Benjamin', 'A obra de arte na era de sua reprodutibilidade técnica', 1935]], liga: ['industria-cultural', 'museu', 'mimese'] },
      { id: 'suprematismo', termo: 'Suprematismo', original: 'супрематизм', ano: 1915, quando: '1915', area: 'movimentos', sente: 'liberdade',
        texto: 'A "supremacia do sentimento puro" na pintura: só formas geométricas sobre o branco, sem objeto nenhum. Malevich apresenta o Quadrado Negro na exposição 0,10 (1915) e o chama de ponto zero da pintura; depois vêm o Quadrado Vermelho (1915) e o Branco sobre Branco (1918).',
        livros: [['Kazimir Malevich', 'Do cubismo e do futurismo ao suprematismo', 1915], ['Kazimir Malevich', 'O mundo não-objetivo', 1927]], liga: ['vanguarda', 'grau-zero', 'espiritual', 'futurismo'] },
      { id: 'musica-esferas', termo: 'Música das esferas', original: 'musica mundana', ano: 1619, quando: 'séc. VI a.C. · 1619', area: 'musica', sente: 'assombro',
        texto: 'A ideia pitagórica de que os planetas, nas suas proporções, soam um acorde que não ouvimos. Boécio a chama de musica mundana (c. 500); Kepler, em A harmonia do mundo (1619), dá a cada planeta uma melodia e descobre a sua terceira lei procurando essa música.',
        livros: [['Boécio', 'De institutione musica', 510], ['Johannes Kepler', 'Harmonices Mundi', 1619], ['Joscelyn Godwin (org.)', 'Harmony of the Spheres: A Sourcebook', 1993]], liga: ['eter', 'contemplacao', 'acorde-mistico'] },
      { id: 'eter', termo: 'Éter', original: 'aithēr', ano: 1887, quando: 'séc. IV a.C. · 1887', area: 'sentidos', sente: 'mistério',
        texto: 'Para Aristóteles, o quinto elemento, de que são feitos os céus. Para a física do século XIX, o meio invisível por onde viajaria a luz, até que o experimento de Michelson e Morley (1887) não o encontrou. Na poesia, continua sendo o meio por onde passa o que é sutil: a tradição, a música, o espírito.',
        livros: [['Aristóteles', 'Do céu', -350], ['Albert Einstein', 'Sobre a eletrodinâmica dos corpos em movimento', 1905]], liga: ['musica-esferas', 'correspondencias', 'espiritual'] },
      { id: 'espiritual', termo: 'O espiritual na arte', original: 'das Geistige in der Kunst', ano: 1911, quando: '1888 · 1911', area: 'sentidos', sente: 'devoção',
        texto: 'A convicção de que a arte abstrata é um caminho para o espírito. Muito dela vem da teosofia de Helena Blavatsky (1888); Kandinsky, Mondrian, Malevich e Scriabin acreditaram nisso, cada um à sua maneira.',
        livros: [['Helena Blavatsky', 'A doutrina secreta', 1888], ['Wassily Kandinsky', 'Do espiritual na arte', 1911], ['Maurice Tuchman (org.)', 'The Spiritual in Art: Abstract Painting 1890–1985', 1986]], liga: ['sinestesia', 'suprematismo', 'acorde-mistico', 'sagrado'] },
      { id: 'leitmotiv', termo: 'Leitmotiv', original: 'Leitmotiv, "motivo condutor"', ano: 1876, quando: '1871 · 1876', area: 'musica', sente: 'reconhecimento',
        texto: 'Um tema musical que representa uma pessoa, um objeto ou uma ideia e volta, transformado, ao longo da obra. Wagner o leva ao máximo no Anel do Nibelungo; o nome se firma nos guias de Hans von Wolzogen (1876). O cinema herdou tudo.',
        livros: [['Hans von Wolzogen', 'Guia temático do Anel do Nibelungo', 1876], ['Thomas Mann', 'Sofrimento e grandeza de Richard Wagner', 1933]], liga: ['obra-total', 'forma-ciclica'] },
      { id: 'forma-ciclica', termo: 'Forma cíclica', original: 'forme cyclique', ano: 1888, quando: '1888 · 1903', area: 'musica', sente: 'reconhecimento',
        texto: 'Uma obra de vários movimentos amarrada pelos mesmos temas, que reaparecem transformados. César Franck a leva à perfeição na Sinfonia em ré menor (1888) e na Sonata para violino (1886); o aluno Vincent d’Indy a transforma em doutrina.',
        livros: [['Vincent d’Indy', 'Cours de composition musicale', 1903], ['Vincent d’Indy', 'César Franck', 1906]], liga: ['leitmotiv', 'contraponto'] },
      { id: 'contraponto', termo: 'Contraponto', original: 'punctus contra punctum', ano: 1725, quando: '1725 · 1909', area: 'musica', sente: 'clareza',
        texto: 'A arte de fazer várias melodias independentes soarem juntas: nota contra nota. Fux a ensina no Gradus ad Parnassum (1725), que Haydn, Mozart e Beethoven estudaram; Bach a leva ao ápice; Taneyev escreve sobre ela o grande tratado russo (1909).',
        livros: [['Johann Joseph Fux', 'Gradus ad Parnassum', 1725], ['J. S. Bach', 'A arte da fuga', 1750], ['Sergei Taneyev', 'Contraponto invertível no estilo estrito', 1909]], liga: ['forma-ciclica', 'weltliteratur', 'nacionalismo'] },
      { id: 'acorde-mistico', termo: 'Acorde místico', original: 'acorde de Prometeu', ano: 1910, quando: '1910', area: 'musica', sente: 'êxtase',
        texto: 'O acorde de seis notas, empilhado em quartas, que serve de centro ao Prometeu de Scriabin (1910): nem maior nem menor, suspenso. Roslavets, depois, constrói os seus "acordes sintéticos" a partir dessa ideia.',
        livros: [['Alexander Scriabin', 'Prometeu, o Poema do Fogo (partitura)', 1910], ['Faubion Bowers', 'Scriabin: A Biography', 1969]], liga: ['sinestesia', 'espiritual', 'atonalidade', 'musica-esferas'] },
      { id: 'atonalidade', termo: 'Atonalidade', original: 'Atonalität', ano: 1911, quando: '1908 · 1911', area: 'musica', sente: 'vertigem',
        texto: 'A música que abandona o centro de uma tonalidade. Schoenberg falava em "emancipação da dissonância": a dissonância não precisa mais se resolver. Do Harmonielehre (1911) ao dodecafonismo, um mundo novo de sons.',
        livros: [['Arnold Schoenberg', 'Harmonielehre', 1911], ['Arnold Schoenberg', 'Estilo e ideia', 1950], ['Alex Ross', 'O resto é ruído', 2007]], liga: ['acorde-mistico', 'vanguarda'] },
      { id: 'nacionalismo', termo: 'Nacionalismo musical', original: 'escolas nacionais', ano: 1867, quando: '1867 · 1928', area: 'musica', sente: 'pertença',
        texto: 'O canto do povo, as danças e as lendas da própria terra levados para a grande forma. O crítico Stasov batiza o "Grupo dos Cinco" russo (1867); Bartók grava camponeses húngaros; Mário de Andrade escreve o programa brasileiro (1928). É o que a abertura chama de "fazer o mesmo".',
        livros: [['Mário de Andrade', 'Ensaio sobre a música brasileira', 1928], ['Béla Bartók', 'A música folclórica húngara', 1924], ['Richard Taruskin', 'Defining Russia Musically', 1997]], liga: ['antropofagia', 'weltliteratur', 'contraponto'] },
      { id: 'antropofagia', termo: 'Antropofagia', original: 'Manifesto Antropófago', ano: 1928, quando: '1928', area: 'movimentos', sente: 'alegria',
        texto: 'Devorar a cultura de fora e transformá-la em coisa nossa, como os tupinambás devoravam o inimigo para ganhar as suas virtudes. Oswald de Andrade publica o manifesto em 1928 ("Tupi, or not tupi, that is the question"); Haroldo de Campos a faz teoria.',
        livros: [['Oswald de Andrade', 'Manifesto Antropófago', 1928], ['Haroldo de Campos', 'Da razão antropofágica', 1981]], liga: ['nacionalismo', 'vanguarda', 'weltliteratur'] },
      { id: 'mecenato', termo: 'Mecenato', original: 'de Mecenas, amigo de Augusto', ano: -30, quando: 'séc. I a.C. · hoje', area: 'instituicoes', sente: 'gratidão',
        texto: 'Quem tem dinheiro e sustenta quem cria. Mecenas protegeu Virgílio e Horácio; os Médici, Florença; Nadezhda von Meck sustentou Tchaikovsky por treze anos (1877–1890), por cartas, sem que os dois jamais marcassem um encontro. Leyland, Freer e os de Menil são as três faces dessa história: o que briga, o que guarda, o que doa.',
        livros: [['Francis Haskell', 'Patrons and Painters', 1963], ['Linda Merrill', 'The Peacock Room: A Cultural Biography', 1998]], liga: ['museu', 'curadoria', 'industria-cultural'] },
      { id: 'gabinete', termo: 'Gabinete de curiosidades', original: 'Wunderkammer', ano: 1565, quando: '1565 · 1655', area: 'instituicoes', sente: 'encanto',
        texto: 'A sala dos colecionadores do Renascimento: conchas, chifres, relógios, pinturas e instrumentos lado a lado, o mundo inteiro num armário. Quiccheberg escreve o primeiro tratado (1565); o Museum Wormianum (1655) é o mais famoso. É o avô do museu.',
        livros: [['Samuel Quiccheberg', 'Inscriptiones vel tituli theatri amplissimi', 1565], ['Ole Worm', 'Museum Wormianum', 1655]], liga: ['museu', 'curadoria'] },
      { id: 'museu', termo: 'Museu', original: 'mouseion, "casa das musas"', ano: 1793, quando: 'séc. III a.C. · 1793', area: 'instituicoes', sente: 'reverência',
        texto: 'De templo das musas em Alexandria a casa pública do patrimônio: o Ashmolean (1683) e, depois da Revolução, o Louvre (1793), aberto a todos. Malraux sonha o "museu imaginário" das reproduções; a Freer Gallery mostra a Sala do Pavão de graça desde 1923.',
        livros: [['André Malraux', 'O museu imaginário', 1947], ['Tony Bennett', 'The Birth of the Museum', 1995]], liga: ['gabinete', 'aura', 'curadoria', 'mecenato'] },
      { id: 'curadoria', termo: 'Curadoria', original: 'curare, "cuidar"', ano: 1969, quando: '1969 · hoje', area: 'instituicoes', sente: 'cuidado',
        texto: 'Curar é cuidar: escolher, juntar e mostrar com um porquê. Em 1969, Harald Szeemann faz de uma exposição (When Attitudes Become Form) uma obra de autor. Esta seção nasce daí: toda escolha assinada, com nome, data e fontes.',
        livros: [['Hans Ulrich Obrist', 'Ways of Curating', 2014], ['Harald Szeemann', 'When Attitudes Become Form (catálogo)', 1969]], liga: ['museu', 'mecenato', 'gabinete', 'contemplacao'] },
      { id: 'art-nouveau', termo: 'Art Nouveau', original: 'Jugendstil · modernismo', ano: 1895, quando: '1895', area: 'movimentos', sente: 'encanto',
        texto: 'A linha curva das plantas em tudo: no ferro do metrô, no vidro, no livro, na joia. O nome vem da loja de Siegfried Bing em Paris, a Maison de l’Art Nouveau (1895). É uma obra de arte total em escala de cidade.',
        livros: [['Gabriel P. Weisberg', 'Art Nouveau Bing: Paris Style 1900', 1986], ['Klaus-Jürgen Sembach', 'Art Nouveau', 1989]], liga: ['japonismo', 'arts-crafts', 'obra-total', 'esteticismo'] },
      { id: 'arts-crafts', termo: 'Arts and Crafts', original: 'Artes e Ofícios', ano: 1853, quando: '1853 · 1890', area: 'movimentos', sente: 'dignidade',
        texto: 'Contra a fábrica que embrutece, a volta do trabalho feito à mão e com prazer. Ruskin escreve "A natureza do gótico" (1853); William Morris faz disso uma empresa, uma tipografia e uma utopia (Notícias de lugar nenhum, 1890).',
        livros: [['John Ruskin', 'As pedras de Veneza ("A natureza do gótico")', 1853], ['William Morris', 'Notícias de lugar nenhum', 1890]], liga: ['bauhaus', 'art-nouveau'] },
      { id: 'bauhaus', termo: 'Bauhaus', original: 'Staatliches Bauhaus, 1919–1933', ano: 1919, quando: '1919 · 1933', area: 'movimentos', sente: 'clareza',
        texto: 'A escola que juntou arte, artesanato e indústria. O manifesto de Gropius (1919) começa assim: "O fim último de toda atividade plástica é a construção!" Kandinsky, Klee e Albers ensinaram lá; o nazismo a fechou em 1933, e ela se espalhou pelo mundo.',
        livros: [['Walter Gropius', 'Manifesto da Bauhaus', 1919], ['Frank Whitford', 'Bauhaus', 1984]], liga: ['obra-total', 'arts-crafts', 'vanguarda'] },
      { id: 'vanguarda', termo: 'Vanguarda', original: 'avant-garde', ano: 1909, quando: '1825 · 1974', area: 'movimentos', sente: 'revolta',
        texto: 'A tropa que vai na frente: a arte que rompe com a tradição e anuncia o futuro, quase sempre com um manifesto. O termo vem do vocabulário militar e dos utopistas de Saint-Simon (1825); Poggioli e Bürger escreveram a sua teoria.',
        livros: [['Renato Poggioli', 'Teoria da arte de vanguarda', 1962], ['Peter Bürger', 'Teoria da vanguarda', 1974]], liga: ['futurismo', 'suprematismo', 'antropofagia', 'kitsch'] },
      { id: 'futurismo', termo: 'Futurismo', original: 'futurismo', ano: 1909, quando: '1909 · 1912', area: 'movimentos', sente: 'revolta',
        texto: 'A velocidade, a máquina e a cidade contra os museus. Marinetti publica o manifesto na primeira página do Le Figaro (20 de fevereiro de 1909); em 1912 os russos dão "Um tapa na cara do gosto público". Do futurismo russo nasce o suprematismo.',
        livros: [['F. T. Marinetti', 'Manifesto do futurismo', 1909], ['Marjorie Perloff', 'The Futurist Moment', 1986]], liga: ['vanguarda', 'suprematismo'] },
      { id: 'industria-cultural', termo: 'Indústria cultural', original: 'Kulturindustrie', ano: 1947, quando: '1944 · 1947', area: 'instituicoes', sente: 'alerta',
        texto: 'A cultura feita em série, como mercadoria, para vender e acalmar. Adorno e Horkheimer cunham o termo na Dialética do esclarecimento: o rádio, o cinema e a música de sucesso como fábrica de iguais. É o contrário de uma curadoria assinada.',
        livros: [['Theodor Adorno e Max Horkheimer', 'Dialética do esclarecimento', 1947]], liga: ['aura', 'kitsch', 'mecenato'] },
      { id: 'kitsch', termo: 'Kitsch', original: 'Kitsch', ano: 1939, quando: '1933 · 1939', area: 'instituicoes', sente: 'ironia',
        texto: 'O efeito pronto, a emoção sem esforço, a imitação da arte. Hermann Broch o chama de "o mal no sistema de valores da arte" (1933); Clement Greenberg o opõe à vanguarda (1939).',
        livros: [['Clement Greenberg', 'Vanguarda e kitsch', 1939], ['Hermann Broch', 'O mal no sistema de valores da arte', 1933]], liga: ['industria-cultural', 'vanguarda'] },
      { id: 'sagrado', termo: 'Sagrado', original: 'das Heilige', ano: 1917, quando: '1917 · 1957', area: 'estetica', sente: 'devoção',
        texto: 'O "totalmente outro" que faz tremer e atrai ao mesmo tempo: mysterium tremendum et fascinans, nas palavras de Rudolf Otto (1917). Eliade mostra como os humanos separam espaços e tempos sagrados do profano. A música, a capela, o canto dos ícones.',
        livros: [['Rudolf Otto', 'O sagrado', 1917], ['Mircea Eliade', 'O sagrado e o profano', 1957]], liga: ['sublime', 'contemplacao', 'espiritual', 'silencio'] },
      { id: 'contemplacao', termo: 'Contemplação', original: 'theoria · contemplatio', ano: 1818, quando: 'séc. IV a.C. · 1818', area: 'estetica', sente: 'serenidade',
        texto: 'Olhar sem querer usar. Para Aristóteles, a vida contemplativa é a mais feliz (Ética a Nicômaco, livro X); para Schopenhauer, diante da arte saímos por um instante da vontade que nos arrasta, e a música é a cópia direta dessa vontade.',
        livros: [['Aristóteles', 'Ética a Nicômaco', -340], ['Arthur Schopenhauer', 'O mundo como vontade e representação', 1818], ['Hartmut Rosa', 'Ressonância', 2016]], liga: ['sagrado', 'silencio', 'musica-esferas', 'sublime'] },
      { id: 'silencio', termo: 'Silêncio', original: '4′33″', ano: 1952, quando: '1952 · 1971', area: 'musica', sente: 'serenidade',
        texto: 'Em 1952, John Cage pôs um pianista diante do piano por quatro minutos e trinta e três segundos sem tocar: a música era o mundo em volta. Feldman, amigo dele, escreveu para a Capela Rothko uma música feita quase só de silêncio.',
        livros: [['John Cage', 'Silêncio', 1961], ['Morton Feldman', 'Give My Regards to Eighth Street', 2000]], liga: ['contemplacao', 'sagrado', 'grau-zero'] },
      { id: 'grau-zero', termo: 'Grau zero', original: 'нуль форм · degré zéro', ano: 1915, quando: '1915 · 1953', area: 'estetica', sente: 'liberdade',
        texto: 'Começar do nada para que tudo possa nascer. Malevich chama o Quadrado Negro de ponto zero da pintura (1915); Barthes procura uma escrita sem ornamento, "branca" (1953). É por isso que a marca do Portal Solar é um quadrado.',
        livros: [['Kazimir Malevich', 'Do cubismo e do futurismo ao suprematismo', 1915], ['Roland Barthes', 'O grau zero da escrita', 1953]], liga: ['suprematismo', 'silencio'] },
      { id: 'dandismo', termo: 'Dandismo', original: 'dandysme', ano: 1845, quando: '1845 · 1863', area: 'movimentos', sente: 'ironia',
        texto: 'A elegância como resistência: fazer da própria vida uma obra, contra a vulgaridade do lucro. Barbey d’Aurevilly escreve sobre Brummell (1845); Baudelaire chama o dandismo de "o último lampejo de heroísmo nas decadências".',
        livros: [['Jules Barbey d’Aurevilly', 'Do dandismo e de George Brummell', 1845], ['Charles Baudelaire', 'O pintor da vida moderna', 1863]], liga: ['decadentismo', 'arte-pela-arte', 'esteticismo'] },
      { id: 'spleen', termo: 'Spleen', original: 'spleen, "baço"', ano: 1869, quando: '1857 · 1869', area: 'sentidos', sente: 'melancolia',
        texto: 'O tédio profundo da cidade moderna, mistura de melancolia e lucidez. Baudelaire o transforma em poesia (as séries "Spleen" das Flores do mal, e O spleen de Paris, 1869). O avesso do êxtase, e às vezes a sua porta.',
        livros: [['Charles Baudelaire', 'O spleen de Paris', 1869], ['Walter Benjamin', 'Charles Baudelaire: um lírico no auge do capitalismo', 1938]], liga: ['decadentismo', 'dandismo'] },
      { id: 'weltliteratur', termo: 'Literatura mundial', original: 'Weltliteratur', ano: 1827, quando: '1827', area: 'instituicoes', sente: 'pertença',
        texto: 'Em 31 de janeiro de 1827, Goethe diz a Eckermann que a época da literatura nacional acabou e começa a da literatura do mundo. É a mesma intuição da abertura: a tradição passa de nação em nação, e cada uma devolve algo seu.',
        livros: [['Johann Peter Eckermann', 'Conversações com Goethe', 1836], ['Erich Auerbach', 'Filologia da literatura mundial', 1952]], liga: ['nacionalismo', 'antropofagia', 'contraponto'] },
    ],

    /* a linha do tempo do post (o ano e o que aconteceu); a régua "expande" o tempo recente */
    linha: [
      [-530, 'Pitágoras e a música das esferas'], [-380, 'Platão, O Banquete'], [-335, 'Aristóteles, Poética'],
      [1619, 'Kepler, A harmonia do mundo'], [1725, 'Fux, Gradus ad Parnassum'], [1757, 'Burke, o sublime e o belo'], [1776, 'O privilégio do Bolshoi'],
      [1790, 'Kant, Crítica da faculdade de julgar'], [1825, 'O Bolshoi de Bové'], [1827, 'Goethe e a literatura mundial'], [1835, 'Gautier, a arte pela arte'],
      [1849, 'Wagner, A obra de arte do futuro'], [1856, 'Cavos reergue o Bolshoi'], [1857, 'Baudelaire, As flores do mal'], [1863, 'Wagner rege em Moscou'],
      [1868, 'Berlioz em Moscou'], [1873, 'Pater, O Renascimento'], [1876, 'A Sala do Pavão'], [1877, 'O Lago dos Cisnes'],
      [1878, 'Whistler contra Ruskin'], [1884, 'Huysmans, Às avessas'], [1886, 'O manifesto do Simbolismo'], [1888, 'Franck, a Sinfonia em ré menor'],
      [1890, 'Dvořák em Moscou'], [1893, 'Aleko, de Rachmaninoff'], [1895, 'A Maison de l’Art Nouveau'], [1904, 'Freer compra a sala'],
      [1909, 'O manifesto futurista; o tratado de Taneyev'], [1910, 'Prometeu, de Scriabin'], [1911, 'Kandinsky e Schoenberg; o Theatro Municipal'],
      [1915, 'O Quadrado Negro'], [1917, 'Otto, O sagrado'], [1919, 'A Bauhaus'], [1922, 'A Semana de 22'], [1923, 'A Freer Gallery abre'],
      [1928, 'O Manifesto Antropófago'], [1930, 'Opus clavicembalisticum; as Bachianas começam'], [1935, 'Benjamin e a aura'], [1936, 'Œdipe, de Enescu'],
      [1938, 'A Ária da Bachianas nº 5'], [1945, 'Cinderela, no Bolshoi'], [1947, 'A indústria cultural'], [1952, 'Cage, 4′33″'],
      [1969, 'Szeemann e a curadoria de autor'], [1971, 'A Capela Rothko'], [1972, 'Feldman, Rothko Chapel'], [2011, 'O Bolshoi reabre'],
      [2016, 'Rosa, Ressonância'], [2026, 'O Portal Solar'],
    ],

    /* duas perguntas para quem lê, no fim */
    perguntas: [
      'Qual destas obras você ouviria hoje, inteira, sem fazer outra coisa?',
      'Quem, na sua terra, fez "o mesmo": levou o que é daqui para a grande tradição?',
    ],
  }];

  var AREAS = [
    ['estetica', 'Estética', '#B0562D'], ['musica', 'Música', '#1B5A44'], ['movimentos', 'Movimentos', '#7E62D6'],
    ['instituicoes', 'Ideias e instituições', '#2F7FD0'], ['sentidos', 'Sentidos e cosmos', '#C9A227'],
  ];

  var api = { posts: POSTS, areas: AREAS };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else raiz.CURADORIA = api;
})(typeof window !== 'undefined' ? window : globalThis);
