/* Dados da linha do tempo (áreas, eras e eventos). Usados por linha-do-tempo.html e pelo hub do Atlas. */
(function () {
  "use strict";
  var AREAS = [
    {code:"mat", name:"Matemática"},
    {code:"fis", name:"Física"},
    {code:"qui", name:"Química"},
    {code:"bio", name:"Biologia"},
    {code:"geo", name:"Geografia"},
    {code:"his", name:"História"},
    {code:"soc", name:"Sociologia"},
    {code:"fil", name:"Filosofia"},
    {code:"ing", name:"Língua Inglesa"}
  ];

  var ERAS = [
    {n:1, id:"e1", title:"Origens e Antiguidade Oriental", range:"até ~600 a.C."},
    {n:2, id:"e2", title:"Grécia e Roma", range:"~600 a.C. – 500 d.C."},
    {n:3, id:"e3", title:"Idade Média", range:"500 – 1450"},
    {n:4, id:"e4", title:"Renascimento e Expansão", range:"1450 – 1600"},
    {n:5, id:"e5", title:"Revolução Científica", range:"1600 – 1700"},
    {n:6, id:"e6", title:"Iluminismo e Revoluções Atlânticas", range:"1700 – 1789"},
    {n:7, id:"e7", title:"Século XIX: Indústria e Nações", range:"1789 – 1900"},
    {n:8, id:"e8", title:"Guerras Mundiais e a Nova Física", range:"1900 – 1945"},
    {n:9, id:"e9", title:"Guerra Fria e Descolonização", range:"1945 – 1991"},
    {n:10, id:"e10", title:"Globalização e Século XXI", range:"1991 – hoje"}
  ];

  // era, ano (texto), área, título curto, nota, referência (mapa da Seleção)
  var EVENTS = [
    [1,"~20.000 a.C.","mat","Osso de Ishango","Os primeiros entalhes de contagem conhecidos, no Congo.","MAT-00"],
    [1,"~3.000 a.C.","qui","Metalurgia e cerâmica","Cobre, vidro, cerveja: os primeiros materiais processados pela mão humana.","QUI-00"],
    [1,"~1.800 a.C.","mat","Plimpton 322","Tábua babilônica em base 60 com ternas pitagóricas — mil anos antes de Pitágoras.","MAT-00"],
    [1,"~1.650 a.C.","mat","Papiro de Rhind","O primeiro \"livro-texto\" de matemática do Egito: frações, áreas, equações simples.","MAT-00"],
    [2,"~600 a.C.","fis","Tales e o âmbar","O âmbar atritado atrai palha; nasce a observação que vira eletricidade 2.200 anos depois.","FIS-11"],
    [2,"~600–400 a.C.","qui","Elementos e átomos","Tales, Empédocles e Demócrito imaginam do que o mundo é feito.","QUI-00"],
    [2,"~600 a.C.","fil","Tales: do mito ao lógos","O primeiro filósofo grego busca uma explicação natural para o cosmos.","FIL-00"],
    [2,"séc. VI a.C.","geo","Anaximandro e Heródoto","O primeiro mapa do mundo conhecido; Heródoto descreve povos e paisagens.","GEO-00"],
    [2,"séc. V a.C.","his","Democracia ateniense","Clístenes e Péricles; Heródoto narra as Guerras Médicas.","HIS-00"],
    [2,"séc. VI–III a.C.","mat","Grécia clássica","Tales, Pitágoras, Euclides, Arquimedes, Apolônio fundam a matemática dedutiva.","MAT-00"],
    [2,"399 a.C.","fil","Morte de Sócrates","Condenado em Atenas por \"corromper a juventude\" — o marco da filosofia moral.","FIL-00"],
    [2,"séc. IV a.C.","fil","Platão e Aristóteles","A Academia e o Liceu: metafísica, ética e lógica ganham sistema.","FIL-00"],
    [2,"~335 a.C.","bio","Aristóteles, zoólogo","Historia Animalium: a primeira classificação sistemática dos seres vivos.","BIO-00"],
    [2,"~300 a.C.","bio","Teofrasto e a botânica","Discípulo de Aristóteles, funda o estudo científico das plantas.","BIO-00"],
    [2,"~250 a.C.","fis","Arquimedes","Alavanca, empuxo, \"Eureka!\": a mecânica antes da mecânica.","FIS-06"],
    [2,"~240 a.C.","geo","Eratóstenes mede a Terra","Com uma vara, uma sombra e uma caravana — a circunferência do planeta.","GEO-00"],
    [2,"séc. III a.C.","fil","Epicuro e os estoicos","Como viver bem diante do acaso e da morte.","FIL-00"],
    [2,"27 a.C.–476 d.C.","his","Império Romano","De Augusto à queda de Roma: direito, engenharia, cristianismo.","HIS-00"],
    [2,"~7 a.C.–150 d.C.","geo","Estrabão e Ptolomeu","A geografia antiga culmina no Almagesto e na Geographia.","GEO-00"],
    [2,"séc. II d.C.","bio","Galeno","Anatomia e fisiologia que dominariam a medicina por 1.400 anos.","BIO-00"],
    [3,"séc. III–VII","qui","Alquimia","Zósimo, depois Jabir e al-Razi: os primeiros laboratórios sistemáticos.","QUI-00"],
    [3,"622/800/1215","his","Hégira, Carlos Magno, Magna Carta","Três fundações medievais: o Islã, o Sacro Império, o limite ao poder do rei.","HIS-00"],
    [3,"séc. V–XIII","fil","Agostinho, Tomás, Avicena, Averróis","Fé e razão dialogam entre Hipona, Paris, Bagdá e Córdoba.","FIL-00"],
    [3,"séc. XIV","soc","Ibn Khaldun","A Muqaddima: coesão social e ciclos de ascensão e queda das civilizações.","SOC-00"],
    [3,"~450–1100","ing","Inglês Antigo","Beowulf e as raízes germânicas da língua inglesa.","ING-00"],
    [3,"1066","ing","Conquista Normanda","O francês invade o inglês: metade do vocabulário de hoje nasce aqui.","ING-00"],
    [3,"séc. V–XII","mat","Zero, seno, álgebra","Índia (Brahmagupta, Aryabhata) e o mundo islâmico (Al-Khwarizmi) refazem a matemática.","MAT-00"],
    [3,"1015","fis","Alhazen","Livro da Óptica: nasce o método experimental — antes de Galileu.","FIS-10"],
    [3,"1154","geo","Mapa de al-Idrisi","A síntese cartográfica árabe, feita para o rei normando da Sicília.","GEO-00"],
    [3,"1202","mat","Fibonacci","Liber Abaci leva os algarismos indo-arábicos e o zero ao Ocidente.","MAT-00"],
    [3,"~1347","his","Peste Negra","Um terço da Europa morre — e o feudalismo começa a ruir.","HIS-00"],
    [3,"~1400","ing","Chaucer","Os Contos de Cantuária: o inglês médio vira literatura maior.","ING-00"],
    [4,"1450–1517","his","Imprensa, Renascimento, Reforma","Gutenberg, os humanistas italianos, Lutero: o mundo europeu se reorganiza.","HIS-00"],
    [4,"séc. XV–XVI","geo","Grandes Navegações","Waldseemüller nomeia a América; Mercator projeta o globo em papel.","GEO-00"],
    [4,"1492/1500","his","Colombo e Cabral","O encontro (e o choque) entre dois mundos.","HIS-00"],
    [4,"1513–1651","fil","Maquiavel e Hobbes","O poder político descrito sem ilusões — e o Leviatã que o justifica.","FIL-05"],
    [4,"1530s","qui","Paracelso","Leva a química da bancada de ouro para a cabeceira do doente.","QUI-00"],
    [4,"1543","bio","Vesalius","De Humani Corporis Fabrica: a anatomia refeita a partir de cadáveres, não de Galeno.","BIO-00"],
    [4,"1543","fis","Copérnico","De Revolutionibus: o Sol, não a Terra, no centro.","FIS-04"],
    [4,"1545","mat","Cardano","Resolve a cúbica e tropeça nos números complexos.","MAT-06"],
    [4,"1564–1616","ing","Shakespeare","Inventa palavras, funde o inglês literário moderno.","ING-00"],
    [5,"1600–1610","fis","Kepler e Galileu","Órbitas elípticas e a luneta apontada para o céu.","FIS-04"],
    [5,"1614","mat","Napier","Os logaritmos — e décadas de contas viram consultas a uma tábua.","MAT-14"],
    [5,"1628","bio","Harvey","A circulação do sangue, provada por matemática e experimento.","BIO-15"],
    [5,"1611","ing","Bíblia do Rei Jaime","O texto que mais moldou o inglês depois de Shakespeare.","ING-00"],
    [5,"1637","mat","Descartes e Fermat","A geometria ganha coordenadas — álgebra e forma se encontram.","MAT-12"],
    [5,"1654","mat","Pascal e Fermat","Uma troca de cartas sobre um jogo interrompido funda a probabilidade.","MAT-09"],
    [5,"1661","qui","Boyle","O Químico Cético: elemento vira conceito científico, não mais mito.","QUI-01"],
    [5,"1665/1676","bio","Hooke e Leeuwenhoek","A célula vista na cortiça; os primeiros micróbios, num microscópio caseiro.","BIO-02"],
    [5,"1687","fis","Newton, Principia","Uma lei para a maçã e para a Lua — a gravitação universal.","FIS-04"],
    [5,"1687","mat","Newton e Leibniz","O cálculo infinitesimal, inventado (e disputado) duas vezes.","MAT-00"],
    [6,"1689–1762","fil","Locke, Montesquieu, Rousseau","Contrato social, separação de poderes, vontade geral.","FIL-05"],
    [6,"1729","ing","Swift","Uma Modesta Proposta: a ironia como arma política.","ING-03"],
    [6,"1735","bio","Lineu","Systema Naturae: nomear e ordenar toda a vida conhecida.","BIO-11"],
    [6,"1748","mat","Euler","Unifica a análise matemática — e^(iπ)+1=0 nasce dessa síntese.","MAT-00"],
    [6,"1755","ing","Dicionário de Johnson","O primeiro grande dicionário sistemático do inglês.","ING-02"],
    [6,"1774–1789","qui","Priestley, Scheele, Lavoisier","O oxigênio isolado, a massa conservada — nasce a química moderna.","QUI-01"],
    [6,"1785","fil","Kant","Fundamentação da Metafísica dos Costumes: o dever como bússola moral.","FIL-03"],
    [6,"1789","his","Revolução Francesa","Liberdade, igualdade, fraternidade — e o fim do Antigo Regime.","HIS-09"],
    [6,"1796","bio","Jenner","A primeira vacina, contra a varíola.","BIO-12"],
    [7,"1801","mat","Gauss","Disquisitiones Arithmeticae: a teoria dos números ganha rigor moderno.","MAT-01"],
    [7,"1808–1811","qui","Dalton e Avogadro","O átomo volta como hipótese científica; nasce o conceito de mol.","QUI-01"],
    [7,"1808–1889","his","Corte, Independência, Império","A família real foge para o Rio; o Brasil se torna nação, depois império.","HIS-00"],
    [7,"1809/1859","bio","Lamarck, Darwin e Wallace","Da herança de caracteres adquiridos à seleção natural.","BIO-08"],
    [7,"séc. XIX","geo","Humboldt e Ritter","Fundam a geografia moderna como ciência da relação entre natureza e sociedade.","GEO-00"],
    [7,"1828","qui","Wöhler","Sintetiza ureia em laboratório — a fronteira entre vida e matéria cai.","QUI-13"],
    [7,"1832","mat","Galois","Morre aos 20 anos, deixando a teoria dos grupos numa carta.","MAT-06"],
    [7,"1833–1877","fis","Faraday, Maxwell, termodinâmica","Eletromagnetismo unificado; Carnot, Joule, Clausius e Boltzmann explicam o calor.","FIS-13"],
    [7,"1838–1867","soc","Comte, Marx, Durkheim","\"Sociologia\" ganha nome, depois método, depois um fundador clássico.","SOC-01"],
    [7,"1838–1839","bio","Teoria celular","Schleiden e Schwann: todo ser vivo é feito de células.","BIO-02"],
    [7,"1859","fil","Mill","Sobre a Liberdade: o limite do Estado sobre o indivíduo.","FIL-05"],
    [7,"1861–1890","bio","Pasteur e Koch","Fim da geração espontânea; a teoria dos germes explica a doença.","BIO-12"],
    [7,"1866","bio","Mendel","As leis da herança, publicadas — e ignoradas por 34 anos.","BIO-05"],
    [7,"1869","qui","Mendeleev","A tabela periódica: ordem que prevê elementos ainda não descobertos.","QUI-04"],
    [7,"1884","his","Conferência de Berlim","As potências europeias dividem a África no papel.","HIS-12"],
    [7,"1884–1887","qui","Arrhenius, van't Hoff, Le Chatelier","Íons em solução, equilíbrio químico, o princípio do deslocamento.","QUI-10"],
    [7,"1888/1889","his","Abolição e República","O fim da escravidão no Brasil; a Primeira República.","HIS-14"],
    [7,"1903–1922","geo","Vidal de la Blache","O possibilismo geográfico: o meio propõe, o homem dispõe.","GEO-00"],
    [7,"1903–1922","soc","Simmel e Weber","A metrópole, a ação social com sentido, o desencantamento do mundo.","SOC-01"],
    [8,"1896–1911","qui","Becquerel, Curie, Rutherford","A radioatividade descoberta; o núcleo atômico, revelado.","QUI-05"],
    [8,"1900s","bio","Redescoberta de Mendel","Morgan e a Drosophila: a genética vira ciência experimental.","BIO-05"],
    [8,"1905","fis","Einstein","Relatividade restrita e o fóton — um só ano, dois mundos novos.","FIS-07"],
    [8,"1909–1913","qui","Haber-Bosch","Fixa nitrogênio do ar em fertilizante — alimenta bilhões, e também arma.","QUI-07"],
    [8,"1914–1945","his","Guerras Mundiais e 1929","Duas guerras, uma quebra financeira, os totalitarismos entre elas.","HIS-17"],
    [8,"1916–1939","qui","Lewis e Pauling","A ligação química explicada por elétrons compartilhados.","QUI-06"],
    [8,"1920s–1940s","soc","Escola de Chicago e Frankfurt","A cidade como laboratório social; a crítica à indústria cultural.","SOC-07"],
    [8,"1920s","fis","Hubble e a física quântica","O universo em expansão; Bohr, Heisenberg, Schrödinger reescrevem o átomo.","FIS-07"],
    [8,"1930s","soc","Sociologia brasileira","Freyre, Buarque de Holanda, Caio Prado Jr., Florestan Fernandes.","SOC-01"],
    [8,"1944–1945","his","Ditadura no Brasil","Estado Novo, FEB na Itália — Vargas entre o fascismo e a democracia.","HIS-15"],
    [9,"1945–1949","ing","Orwell","Animal Farm e 1984: a distopia como crítica política.","ING-03"],
    [9,"1944–1953","bio","Franklin, Watson e Crick","A Foto 51 e a dupla hélice — a estrutura do DNA.","BIO-04"],
    [9,"1947–1991","his","Guerra Fria","EUA e URSS dividem o mundo por quase meio século.","HIS-18"],
    [9,"1951–1963","fil","Hannah Arendt","As Origens do Totalitarismo; a banalidade do mal em Jerusalém.","FIL-06"],
    [9,"1953","qui","Sanger, Watson-Crick, Ziegler-Natta","O código da vida decifrado; a era dos polímeros sintéticos começa.","QUI-14"],
    [9,"1960–1980","soc","Bourdieu, Foucault, Goffman, Geertz","Capital cultural, poder disciplinar, o teatro do cotidiano, a cultura como texto.","SOC-03"],
    [9,"1963","ing","\"I Have a Dream\"","Martin Luther King Jr. em Washington — o discurso como ato político.","ING-03"],
    [9,"1964–1985","his","Ditadura Civil-Militar","Vinte e um anos de regime militar no Brasil.","HIS-20"],
    [9,"1970s","bio","Lynn Margulis","A endossimbiose: mitocôndrias e cloroplastos já foram bactérias livres.","BIO-02"],
    [9,"1970s","geo","Geografia crítica","Lacoste, Harvey, Milton Santos: o espaço como produto social.","GEO-00"],
    [9,"1971","fil","Rawls","Uma Teoria da Justiça: o \"véu da ignorância\" redesenha o liberalismo.","FIL-05"],
    [9,"1974–1987","qui","Molina-Rowland e Montreal","O buraco de ozônio explicado — e reparado por um acordo global.","QUI-15"],
    [9,"1986","ing","Ngũgĩ e Soyinka","A literatura africana em inglês ganha o Nobel e recusa o colonizador.","ING-05"],
    [9,"1989","his","Queda do Muro de Berlim","O símbolo mais visível do fim da Guerra Fria.","HIS-23"],
    [10,"1990–2003","bio","Projeto Genoma Humano","Todo o DNA humano, sequenciado — e Carl Woese redesenha a árvore da vida.","BIO-11"],
    [10,"1990–2010s","soc","Castells, Bauman, Beck, Crenshaw","Sociedade em rede, modernidade líquida, risco global, interseccionalidade.","SOC-06"],
    [10,"1990–2000s","geo","Globalização e geotecnologias","Redes, GPS, big data reorganizam o espaço mundial.","GEO-08"],
    [10,"2009","ing","Adichie","\"The Danger of a Single Story\": por que uma só narrativa distorce um povo.","ING-01"],
    [10,"2012","bio","CRISPR","Doudna e Charpentier: editar genes fica preciso e barato.","BIO-06"],
    [10,"2015/2019","fis","Ondas gravitacionais","Einstein confirmado cem anos depois; a primeira foto de um buraco negro.","FIS-07"]
  ];
  window.LINHA = { AREAS: AREAS, ERAS: ERAS, EVENTS: EVENTS };
})();
